# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82123dceb4bed06991691d6bb5bc29d875b76a174b723218b6c66bd5ce54d91f7deab7e4e47a2ef9ffc2307e7583570bbf73c3b7b1f6515ac078801f811143e3

test:
  secret_key_base: c141e09afb533c095f9a42b093174e9c3889306fc422c4ac5614bd31522d7e4a00c407b0966def6e962bcdfd3c5eecb78cbee7a002f319188c6433130ebbf882

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
